# Generated by Django 5.2.1 on 2025-06-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
