# Generated by Django 5.2.1 on 2025-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_completed',
            field=models.BooleanField(default=False),
        ),
    ]
