# Generated by Django 5.2.1 on 2025-06-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
